[project]
name = 'Decentralized-Project-Management-Agile-Methodology-Support'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.agile-coach-verification]
path = 'contracts/agile-coach-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.backlog-coordination]
path = 'contracts/backlog-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
